version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datadriven-portfolio
    ports:
      - "5173:5173"
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
